name: den
channels:
  - pytorch
  - nvidia
  - conda-forge
  - robostack
  - defaults
  - senyan.dev                # temporary for cudatoolkit-dev=11.8, while awaiting for conda-forge
dependencies:
  - cudatoolkit-dev=11.8
  - setuptools=59.5.0
  - python=3.8
  - pip=21.3.1
  - easydict=1.9
  - numpy=1.24.4
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - torchvision=0.17.0
  - tensorboard=2.11.2
  - pytorch-lightning=1.4.9
  - torchmetrics=0.6.2
  - hdf5plugin=3.2.0
  - h5py=3.1.0
  - ros-noetic-rosbag=1.15.13
  - absl-py=2.0.0
  - opencv=4.5.2              # Matches existing ESIM C++ OpenCV version for 
                              # identical imread() RGB-to-grayscale behaviour
  - pip:
    - roma==1.2.7
    - pypose==0.6.7
    - lpips==0.1.4
    - nerfacc==0.3.1
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
